version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.production
      - backend/.env.production
    environment:
      # Override specific variables for Docker environment
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
    volumes:
      # Persistent data storage
      - app_data:/app/backend/database
      - app_logs:/app/logs
    restart: on-failure:3
    stop_signal: SIGTERM
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://0.0.0.0:3001/api/test', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local